---
- import_playbook: ./wsl.yml

- import_playbook: ./win.yml

- hosts: all
  become: true
  become_user: root
  tasks:
    - name: restart docker
      service:
        name: docker
        state: restarted

    - name: enable docker
      service:
        name: docker
        enabled: yes
