# サービス固有の設定を実行
- hosts: all
  become: true
  become_user: root
  roles:
    - { role: "auto_package_upgrade"}
    - { role: "locale"}
    - { role: "timezone"}
    - { role: "dev_tool_install"}
    - { role: "sshd"}
    - { role: "ansible"}
  tasks:
    # systemdにconfigsを読み直すように強制する
    # servicedの再読込（/etc/systemd/system/のファイルを変更した場合に必須）
    - name: just force systemd to reread configs
      systemd:
        daemon_reload: yes
      ignore_errors: true
