---
- hosts: all
  become: no
  tasks:
    - name: set wsl .gitconfig.j2
      template:
        src: home/.gitconfig.j2
        dest: "/home/{{ user_name }}/.gitconfig"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        backup: true

    - name: set wsl .gitignore_global
      template:
        src: home/.gitignore_global.j2
        dest: "/home/{{ user_name }}/.gitignore_global"
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        backup: true

    - name: "put win {{ wsl_mount_dir }}c/Users/{{ user_name }}/.gitconfig"
      template:
        src: win/.gitconfig.j2
        dest: "{{ wsl_mount_dir }}c/Users/{{ user_name }}/.gitconfig"
        backup: true

    - name: "put win {{ wsl_mount_dir }}c/Users/{{ user_name }}/.gitconfig"
      template:
        src: win/.gitignore_global
        dest: "{{ wsl_mount_dir }}c/Users/{{ user_name }}/.gitignore_global"
        backup: true
