all:
  vars:
    ansible_ssh_port: 22
    ansible_python_interpreter: /usr/bin/python3
  children:
    dev:
      vars:
        ansible_connection: local
      children:
        wsl_dev:
          hosts:
            localhost: {}
    wsl:
      children:
        wsl_dev: {}
