- hosts: all
  tasks:
    - name: 電源接続時にモニターを切らないようにする
      tags: setting
      win_command: powercfg -x monitor-timeout-ac 0
      check_mode: no

    - name: PolicyFileEditorの存在確認
      tags: setting
      win_shell: Get-Package | ? { $_.Name -eq "PolicyFileEditor" }
      register: exist_pfe

    - name: PolicyFileEditorをインストール
      tags: setting
      win_shell: Install-Module -Name PolicyFileEditor -Force
      when: not exist_pfe.stdout

    - name: PolicyFileEditorを使ってローカルグループポリシーを変更する
      # 大抵はOS再起動後に適用される
      tags: setting
      win_shell: ipmo PolicyFileEditor; Set-PolicyFileEntry -Path "{{ item.path | default('$env:windir\System32\GroupPolicy\Machine\registry.pol') }}" -Key "{{ item.key }}" -ValueName {{ item.value_name }} -Data {{ item.data }} -Type {{ item.type | default('DWord') }}
      with_items:
        # 「自動更新を構成する」を有効に
        - key: Software\Policies\Microsoft\Windows\WindowsUpdate\AU
          value_name: NoAutoUpdate
          data: 0
        # 「自動更新を構成する」で"4 - 自動ダウンロードしインストール日時を選択"
        - key: Software\Policies\Microsoft\Windows\WindowsUpdate\AU
          value_name: AUOptions
          data: 4
        # 「自動更新を構成する」で"自動メンテナンス時にインストールする"にチェック
        - key: Software\Policies\Microsoft\Windows\WindowsUpdate\AU
          value_name: AutomaticMaintenanceEnabled
          data: 1
        # 「自動更新を構成する」の"インストールを実行する日"（この設定は使用されない）
        - key: Software\Policies\Microsoft\Windows\WindowsUpdate\AU
          value_name: ScheduledInstallDay
          data: 0
        # 「自動更新を構成する」の"インストールを実行する時間"（この設定は使用されない）
        - key: Software\Policies\Microsoft\Windows\WindowsUpdate\AU
          value_name: ScheduledInstallTime
          data: 3
        # 「自動更新を構成する」で"ほかのMicrosoft製品の更新プログラムのインストール"にチェック
        - key: Software\Policies\Microsoft\Windows\WindowsUpdate\AU
          value_name: AllowMUUpdateService
          data: 1
        # 「自動更新を直ちにインストールすることを許可する」を無効に
        - key: Software\Policies\Microsoft\Windows\WindowsUpdate\AU
          value_name: AutoInstallMinorUpdates
          data: 0
        # 「スケジュールされた自動更新のインストールで、ログオンしているユーザーがいる場合には自動的に再起動しない」を有効に
        - key: Software\Policies\Microsoft\Windows\WindowsUpdate\AU
          value_name: NoAutoRebootWithLoggedOnUsers
          data: 1
        # 「Cortanaを許可する」を無効に
        - key: Software\Policies\Microsoft\Windows\Windows Search
          value_name: AllowCortana
          data: 0

    - name: 各種レジストリによる設定変更
      tags: setting
      win_regedit:
        key: '{{ item.key }}'
        value: '{{ item.value }}'
        data: '{{ item.data }}'
        datatype: '{{ item.datatype | default("dword") }}'
      with_items:
        # 固定キー機能がキー入力によって有効になるのを防ぐ
        # https://msdn.microsoft.com/en-us/library/dd373652%28VS.85%29.aspx
        - key: HKCU:\Control Panel\Accessibility\StickyKeys
          value: Flags
          data: 2
          datatype: string
        # 「右シフトキーが8秒間押されたときにフィルターキーを有効にする」の無効化
        - key: HKCU:\Control Panel\Accessibility\Keyboard Response
          value: Flags
          data: 98
          datatype: string
        # 「ウィンドウを画面の横または隅にドラッグしたときに自動的に整列する」の無効化
        - key: HKCU:\Control Panel\Desktop
          value: WindowArrangementActive
          data: 0
          datatype: string
        # 「ときどきスタート画面におすすめを表示する」の無効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
          value: SystemPaneSuggestionsEnabled
          data: 0
        # 「Windowsを使用するためのヒントやおすすめの方法を取得」の無効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager
          value: SoftLandingEnabled
          data: 0
        # エクスプローラーの「隠しファイル、隠しフォルダー、および隠しドライブを表示する」の有効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
          value: Hidden
          data: 1
        # エクスプローラーの「登録されている拡張子は表示しない」の無効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
          value: HideFileExt
          data: 0
        # エクスプローラーの「エクスプローラーで開く」を"PC"に
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
          value: LaunchTo
          data: 1
        # エクスプローラーの「別のプロセスでフォルダーウィンドウを開く」の有効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
          value: SeparateProcess
          data: 1
        # エクスプローラーの「保護されたオペレーションシステムファイルを表示しない」の無効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
          value: ShowSuperHidden
          data: 1
        # 「小さいタスクバーボタンを使う」の有効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
          value: TaskbarSmallIcons
          data: 1
        # 「（前略）メニューでコマンドプロンプトをWindows PowerShellに置き換える」の有効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
          value: DontUsePowerShellOnWinX
          data: 0
        # 「タスクバーを固定する」の無効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced
          value: TaskbarSizeMove
          data: 1
        # エクスプローラーの「タイトルバーに完全なパスを表示する」の有効化
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\CabinetState
          value: FullPath
          data: 1
        # タスクバーに「検索アイコンを表示する」
        - key: HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Search
          value: SearchboxTaskbarMode
          data: 1
        # 「このコンピューターへのリモートアシスタンス接続を許可する」の無効化
        - key: HKLM:\SYSTEM\CurrentControlSet\Control\Remote Assistance
          value: fAllowToGetHelp
          data: 0
        # 「このコンピューターへのリモート接続を許可する」を選択
        - key: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server
          value: fDenyTSConnections
          data: 0
        # 「ネットワークレベル認証でリモートデスクトップを実行しているコンピューターからのみ接続を許可する」の無効化
        #        - key: HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp
        #          value: UserAuthentication
        #          data: 0
        # Windows Timeサービスが問い合わせを行うntpサーバをtime.google.comに変更し、Client/Serverモードとし、問い合わせ間隔をMinPollIntervalからMaxPollIntervalの間とする
        - key: HKLM:\SYSTEM\CurrentControlSet\Services\W32Time\Parameters
          value: NTPServer
          data: time.google.com,0x8
          datatype: string
        # Windows Timeサービスがntpサーバーに問い合わせを行う最小間隔を2^8秒とする
        - key: HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Config
          value: MinPollInterval
          data: 8
        # Windows Timeサービスがntpサーバーに問い合わせを行う最大間隔を2^12秒とする
        - key: HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Config
          value: MaxPollInterval
          data: 12
        # Windows Timeサービスがslewモードで同期を行う最大の時刻差を10分とする
        - key: HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Config
          value: MaxAllowedPhaseOffset
          data: 600
        # Windows Timeサービスがslewモードで同期を行う際の修正実行サイクルを100000clock ticksとする
        # https://msdn.microsoft.com/ja-jp/library/cc773263%28v=ws.10%29.aspx によれば1clock ticks = 10^-7秒
        - key: HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Config
          value: UpdateInterval
          data: 100000
        # Windows Timeサービスが同期を実施する、ntpサーバーに対する最大の遅れ秒数を上限なしとする
        - key: HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Config
          value: MaxPosPhaseCorrection
          data: 4294967295
        # Windows Timeサービスが同期を実施する、ntpサーバーに対する最大の進み秒数を10分にする
        - key: HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Config
          value: MaxNegPhaseCorrection
          data: 600
        # Windows Timeサービスのログをイベントに出力する
        - key: HKLM:\SYSTEM\CurrentControlSet\services\W32Time\Config
          value: EventLogFlags
          data: 3

    - name: Windows Timeサービスにネットワーク接続時のみ起動するトリガーイベントを設定する
      # https://support.microsoft.com/ja-jp/kb/2385818
      tags: setting
      win_command: sc triggerinfo w32time start/networkon stop/networkoff
      check_mode: no

    - name: タスクスケジューラーの履歴を有効化する
      tags: setting
      win_command: wevtutil sl Microsoft-Windows-TaskScheduler/Operational /e:true
      check_mode: no

    - name: Windows Defenderの更新をタスクスケジューラーで実施する
      tags: setting
      win_shell: Register-ScheduledTask -TaskPath {{ "\ " }}-TaskName "Windows Defender" -User SYSTEM -RunLevel Highest -Action (New-ScheduledTaskAction -Execute "C:\Program Files\Windows Defender\MpCmdRun.exe" -Argument "-SignatureUpdate -MMPC") -Trigger (New-ScheduledTaskTrigger -Once -At "2016/1/1 00:01" -RepetitionInterval "01:30:00" -RandomDelay "00:01:00") -Settings (New-ScheduledTaskSettingsSet -RunOnlyIfNetworkAvailable) -Force

    - name: アプリのインストール
      tags: app
      win_chocolatey:
        name: '{{ item.name }}'
        ignore_dependencies: '{{ item.ignore_dependencies | default("no") }}'
        ignore_checksums: '{{ item.ignore_checksums | default("no") }}'
      with_items:
        - name: everything
        - name: linkshellextension
        - name: sudo
        - name: mobaxterm
          ignore_checksums: yes
        - name: sublimetext3
        - name: googlechrome
        - name: firefox
        - name: adobereader
        - name: sysinternals
        - name: dropbox
          ignore_dependencies: yes
        - name: keepass
        - name: keepass-keepasshttp
        - name: winscp
