---
- hosts: all
  become: no
  tasks:
    - name: "create {{ user_name }} .ssh/ dicrectory"
      file:
        path: "{{ wsl_mount_dir }}c/Users/{{ user_name }}/.ssh"
        state: directory

    - name: "put {{ wsl_mount_dir }}c/Users/{{ user_name }}/.ssh/config"
      template:
        src: win/.ssh/config
        dest: "{{ wsl_mount_dir }}c/Users/{{ user_name }}/.ssh/config"
        backup: true


