- name: open ssh server install
  apt:
    name: openssh-server
    update_cache: yes
    cache_valid_time: 3600
  tags: ssh

# sshd
- name: sshd is configured
  notify:
    - restart ssh
    - enable ssh
  template:
    src: "sshd_config.j2"
    dest: "/etc/ssh/sshd_config"
    owner: root
    group: root
    mode: 0644
  tags: ssh
